"/dev/video0": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"
"/dev/video1": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"
"/dev/video2": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"
"/dev/video3": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"
"/dev/video4": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"
"/dev/video5": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"
"/dev/video6": "/home/roger/catkinws/src/camera_driver/config/senyun_FOV120/960_540.yaml"